=== dberlind/CoffeeAPI/schemas/drinkItemValidationSchema.json
{
  "type"     :"object",
  "$schema"  : "http://json-schema.org/draft-04/schema",
  "id"       : "http://jsonschema.net",
  "required" : ["drinkName","drinkFamily","drinkBlurb","drinkHotCold","drinkWikiURL"],
  "properties": {
    "drinkName"   : {
      "type": "string",
      "minlength" : 3
    },
    "drinkFamily" : {
      "type": "string",
      "enum": ["Black Espresso", "Milked Espresso"]
    },
    "drinkBlurb"  : {
      "type":  "string",
      "minLength" : 20
    },
    "drinkHotCold": {
      "type": "string",
      "enum": ["Hot", "Cold"]
    },
    "drinkWikiURL": {
      "type": "string",
      "format": "uri"
    }
  }
}

=== dberlind/CoffeeAPI/examples/drinkItemPost.json
{
      "drinkName"   : "Espresso Romano",
      "drinkFamily" : "Black Espresso",
      "drinkBlurb"  : "An espresso Romano is a shot of espresso with a slice of lemon served on the side. The lemon can be run along the rim of the cup as a way to accentuate the espresso's sweetness.",
      "drinkHotCold": "Hot",
      "drinkWikiURL": "https://en.wikipedia.org/wiki/List_of_coffee_drinks#Espresso_Romano"
}
